version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.8
jobs:
  build:
    docker:
      - image: 'circleci/python:3.7.3'
    working_directory: ~/project
    steps:
      - checkout
      - run: rm -rf .git 
      - run: rm -rf .circleci 
      - run: rm -f web.config
      - run: ls
      - aws-s3/sync:
          from: ~/project
          to: 's3://progression.myunidays.com/'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
            --dryrun
          overwrite: true