version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.8
jobs:
  build:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - checkout
      - aws-s3/sync:
          from: /
          to: 's3://progression.myunidays.com'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true