version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.8
jobs:
  build-and-awssync:
    docker:
      - image: 'circleci/node:lts'
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Compile sass
          command: |
            sudo npm install -g grunt
            npm install
            grunt build:prod
      - aws-s3/sync:
          from: ~/project/build
          to: 's3://progression.myunidays.com/'
          arguments: |
            --delete \
            --exclude "build/web.config" \
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build-and-awssync:
          filters:
            branches:
              only: master